// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Bugs._Bug;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Info extends Table {
  public static Info getRootAsInfo(ByteBuffer _bb) { return getRootAsInfo(_bb, new Info()); }
  public static Info getRootAsInfo(ByteBuffer _bb, Info obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Info __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String summary() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer summaryAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String description() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createInfo(FlatBufferBuilder builder,
      int summaryOffset,
      int descriptionOffset) {
    builder.startObject(2);
    Info.addDescription(builder, descriptionOffset);
    Info.addSummary(builder, summaryOffset);
    return Info.endInfo(builder);
  }

  public static void startInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSummary(FlatBufferBuilder builder, int summaryOffset) { builder.addOffset(0, summaryOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(1, descriptionOffset, 0); }
  public static int endInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

