// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Slices._Slice._SourceFile;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Function extends Table {
  public static Function getRootAsFunction(ByteBuffer _bb) { return getRootAsFunction(_bb, new Function()); }
  public static Function getRootAsFunction(ByteBuffer _bb, Function obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Function __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public _fast._Slices._Slice._SourceFile._Function.Variable variable(int j) { return variable(new _fast._Slices._Slice._SourceFile._Function.Variable(), j); }
  public _fast._Slices._Slice._SourceFile._Function.Variable variable(_fast._Slices._Slice._SourceFile._Function.Variable obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int variableLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int type() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFunction(FlatBufferBuilder builder,
      int variableOffset,
      int nameOffset,
      int type) {
    builder.startObject(3);
    Function.addType(builder, type);
    Function.addName(builder, nameOffset);
    Function.addVariable(builder, variableOffset);
    return Function.endFunction(builder);
  }

  public static void startFunction(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addVariable(FlatBufferBuilder builder, int variableOffset) { builder.addOffset(0, variableOffset, 0); }
  public static int createVariableVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVariableVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(2, type, 0); }
  public static int endFunction(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

