// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Slices._Slice._SourceFile._Function._Variable;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Position extends Table {
  public static Position getRootAsPosition(ByteBuffer _bb) { return getRootAsPosition(_bb, new Position()); }
  public static Position getRootAsPosition(ByteBuffer _bb, Position obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int lineno() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int type() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int deltaLineno() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createPosition(FlatBufferBuilder builder,
      int lineno,
      int type,
      int delta_lineno) {
    builder.startObject(3);
    Position.addDeltaLineno(builder, delta_lineno);
    Position.addType(builder, type);
    Position.addLineno(builder, lineno);
    return Position.endPosition(builder);
  }

  public static void startPosition(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addLineno(FlatBufferBuilder builder, int lineno) { builder.addInt(0, lineno, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(1, type, 0); }
  public static void addDeltaLineno(FlatBufferBuilder builder, int deltaLineno) { builder.addInt(2, deltaLineno, 0); }
  public static int endPosition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

