// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Delta._Diff;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Del extends Table {
  public static Del getRootAsDel(ByteBuffer _bb) { return getRootAsDel(_bb, new Del()); }
  public static Del getRootAsDel(ByteBuffer _bb, Del obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Del __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int src() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createDel(FlatBufferBuilder builder,
      int src) {
    builder.startObject(1);
    Del.addSrc(builder, src);
    return Del.endDel(builder);
  }

  public static void startDel(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSrc(FlatBufferBuilder builder, int src) { builder.addInt(0, src, 0); }
  public static int endDel(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

