// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Data;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous4 extends Table {
  public static Anonymous4 getRootAsAnonymous4(ByteBuffer _bb) { return getRootAsAnonymous4(_bb, new Anonymous4()); }
  public static Anonymous4 getRootAsAnonymous4(ByteBuffer _bb, Anonymous4 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous4 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public _fast.Element element() { return element(new _fast.Element()); }
  public _fast.Element element(_fast.Element obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public _fast.Log log() { return log(new _fast.Log()); }
  public _fast.Log log(_fast.Log obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public _fast.Delta delta() { return delta(new _fast.Delta()); }
  public _fast.Delta delta(_fast.Delta obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public _fast.Pairs pairs() { return pairs(new _fast.Pairs()); }
  public _fast.Pairs pairs(_fast.Pairs obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public _fast.Slices slices() { return slices(new _fast.Slices()); }
  public _fast.Slices slices(_fast.Slices obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public _fast.Bugs bugs() { return bugs(new _fast.Bugs()); }
  public _fast.Bugs bugs(_fast.Bugs obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createAnonymous4(FlatBufferBuilder builder,
      int elementOffset,
      int logOffset,
      int deltaOffset,
      int pairsOffset,
      int slicesOffset,
      int bugsOffset) {
    builder.startObject(6);
    Anonymous4.addBugs(builder, bugsOffset);
    Anonymous4.addSlices(builder, slicesOffset);
    Anonymous4.addPairs(builder, pairsOffset);
    Anonymous4.addDelta(builder, deltaOffset);
    Anonymous4.addLog(builder, logOffset);
    Anonymous4.addElement(builder, elementOffset);
    return Anonymous4.endAnonymous4(builder);
  }

  public static void startAnonymous4(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addElement(FlatBufferBuilder builder, int elementOffset) { builder.addOffset(0, elementOffset, 0); }
  public static void addLog(FlatBufferBuilder builder, int logOffset) { builder.addOffset(1, logOffset, 0); }
  public static void addDelta(FlatBufferBuilder builder, int deltaOffset) { builder.addOffset(2, deltaOffset, 0); }
  public static void addPairs(FlatBufferBuilder builder, int pairsOffset) { builder.addOffset(3, pairsOffset, 0); }
  public static void addSlices(FlatBufferBuilder builder, int slicesOffset) { builder.addOffset(4, slicesOffset, 0); }
  public static void addBugs(FlatBufferBuilder builder, int bugsOffset) { builder.addOffset(5, bugsOffset, 0); }
  public static int endAnonymous4(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

