// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Element._Literal;

public final class LiteralType {
  private LiteralType() { }
  public static final int dummy_type = 0;
  public static final int number_type = 1;
  public static final int char_type = 2;
  public static final int string_type = 3;
  public static final int boolean_type = 4;
  public static final int null_type = 5;

  public static final String[] names = { "dummy_type", "number_type", "char_type", "string_type", "boolean_type", "null_type", };

  public static String name(int e) { return names[e]; }
}

