// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Element;

public final class DiffType {
  private DiffType() { }
  public static final int MATCHED = 0;
  public static final int ADDED = 1;
  public static final int DELETED = 2;
  public static final int CHANGED_FROM = 3;
  public static final int CHANGED_TO = 4;

  public static final String[] names = { "MATCHED", "ADDED", "DELETED", "CHANGED_FROM", "CHANGED_TO", };

  public static String name(int e) { return names[e]; }
}

