// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Log._Commit;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous3 extends Table {
  public static Anonymous3 getRootAsAnonymous3(ByteBuffer _bb) { return getRootAsAnonymous3(_bb, new Anonymous3()); }
  public static Anonymous3 getRootAsAnonymous3(ByteBuffer _bb, Anonymous3 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Committer committer() { return committer(new Committer()); }
  public Committer committer(Committer obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createAnonymous3(FlatBufferBuilder builder,
      int committerOffset) {
    builder.startObject(1);
    Anonymous3.addCommitter(builder, committerOffset);
    return Anonymous3.endAnonymous3(builder);
  }

  public static void startAnonymous3(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCommitter(FlatBufferBuilder builder, int committerOffset) { builder.addOffset(0, committerOffset, 0); }
  public static int endAnonymous3(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

