// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Delta._Diff;

public final class DeltaType {
  private DeltaType() { }
  public static final int MATCH = 0;
  public static final int ADD = 1;
  public static final int DEL = 2;
  public static final int MOVE = 3;
  public static final int UPDATE = 4;

  public static final String[] names = { "MATCH", "ADD", "DEL", "MOVE", "UPDATE", };

  public static String name(int e) { return names[e]; }
}

