#!/bin/bash
p=/Users/yijunyu/mirror/github.com/yijunyu/gumtree
function compile() {
	gradle build
}
compile
cp build/libs/gen.pb-2.1.0-SNAPSHOT.jar $p/gumtree-20170805-2.1.0-SNAPSHOT/lib/
cd $p
fast Hello1.java Hello1.pb
fast Hello2.java Hello2.pb
gumtree-20170805-2.1.0-SNAPSHOT/bin/gumtree webdiff Hello1.pb Hello2.pb
cd -
