// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Slices._Slice;

public final class ChangeType {
  private ChangeType() { }
  public static final int UNCHANGED = 0;
  public static final int ADD = 1;
  public static final int DEL = 2;

  public static final String[] names = { "UNCHANGED", "ADD", "DEL", };

  public static String name(int e) { return names[e]; }
}

