#!/bin/bash
function compile() {
	gradle build -x checkstyleMain -x test
}
compile
cd .. > /dev/null
gumtree=gumtree-$(date '+%Y%m%d')-2.1.0-SNAPSHOT
if [ ! -d $gumtree/lib/ ]; then
	gradle build -x checkstyleMain -x test
	unzip dist/build/distributions/$gumtree.zip
fi
cp core/build/libs/core-2.1.0-SNAPSHOT.jar $gumtree/lib/
fast Hello1.java Hello1.fbs
fast Hello2.java Hello2.fbs
$gumtree/bin/gumtree diff Hello1.fbs Hello2.fbs
#cp -r $gumtree/* /usr/local/
#cd - > /dev/null
