// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Element;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous0 extends Table {
  public static Anonymous0 getRootAsAnonymous0(ByteBuffer _bb) { return getRootAsAnonymous0(_bb, new Anonymous0()); }
  public static Anonymous0 getRootAsAnonymous0(ByteBuffer _bb, Anonymous0 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous0 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int kind() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int smaliKind() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createAnonymous0(FlatBufferBuilder builder,
      int kind,
      int smali_kind) {
    builder.startObject(2);
    Anonymous0.addSmaliKind(builder, smali_kind);
    Anonymous0.addKind(builder, kind);
    return Anonymous0.endAnonymous0(builder);
  }

  public static void startAnonymous0(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKind(FlatBufferBuilder builder, int kind) { builder.addInt(0, kind, 0); }
  public static void addSmaliKind(FlatBufferBuilder builder, int smaliKind) { builder.addInt(1, smaliKind, 0); }
  public static int endAnonymous0(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

