// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Element;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Anonymous1 extends Table {
  public static Anonymous1 getRootAsAnonymous1(ByteBuffer _bb) { return getRootAsAnonymous1(_bb, new Anonymous1()); }
  public static Anonymous1 getRootAsAnonymous1(ByteBuffer _bb, Anonymous1 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Anonymous1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Unit unit() { return unit(new Unit()); }
  public Unit unit(Unit obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public Literal literal() { return literal(new Literal()); }
  public Literal literal(Literal obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createAnonymous1(FlatBufferBuilder builder,
      int unitOffset,
      int literalOffset) {
    builder.startObject(2);
    Anonymous1.addLiteral(builder, literalOffset);
    Anonymous1.addUnit(builder, unitOffset);
    return Anonymous1.endAnonymous1(builder);
  }

  public static void startAnonymous1(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUnit(FlatBufferBuilder builder, int unitOffset) { builder.addOffset(0, unitOffset, 0); }
  public static void addLiteral(FlatBufferBuilder builder, int literalOffset) { builder.addOffset(1, literalOffset, 0); }
  public static int endAnonymous1(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

