// automatically generated by the FlatBuffers compiler, do not modify

package _fast;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Slices extends Table {
  public static Slices getRootAsSlices(ByteBuffer _bb) { return getRootAsSlices(_bb, new Slices()); }
  public static Slices getRootAsSlices(ByteBuffer _bb, Slices obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Slices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public _fast._Slices.Slice slice(int j) { return slice(new _fast._Slices.Slice(), j); }
  public _fast._Slices.Slice slice(_fast._Slices.Slice obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int sliceLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createSlices(FlatBufferBuilder builder,
      int sliceOffset) {
    builder.startObject(1);
    Slices.addSlice(builder, sliceOffset);
    return Slices.endSlices(builder);
  }

  public static void startSlices(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSlice(FlatBufferBuilder builder, int sliceOffset) { builder.addOffset(0, sliceOffset, 0); }
  public static int createSliceVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSliceVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSlices(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

