// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Element._Unit;

public final class LanguageType {
  private LanguageType() { }
  public static final int DUMMY = 0;
  public static final int ALL = 1;
  public static final int OO = 2;
  public static final int CXX = 3;
  public static final int C = 4;
  public static final int C_FAMILY = 5;
  public static final int JAVA = 6;
  public static final int CSHARP = 7;
  public static final int OBJECTIVE_C = 8;

  public static final String[] names = { "DUMMY", "ALL", "OO", "CXX", "C", "C_FAMILY", "JAVA", "CSHARP", "OBJECTIVE_C", };

  public static String name(int e) { return names[e]; }
}

