// automatically generated by the FlatBuffers compiler, do not modify

package _fast._Pairs._Pair;

public final class CloneType {
  private CloneType() { }
  public static final int MAYBE = 0;
  public static final int YES = 1;
  public static final int NO = 2;

  public static final String[] names = { "MAYBE", "YES", "NO", };

  public static String name(int e) { return names[e]; }
}

